Drop mix_stderr=False from CliRunner()
Upstream deprecated the option to mangle original stdout and stderr,
and instead provides result.output that copies the original streams
into a new mixed stream, in proper terminal order.

Passing mix_stderr is invalid since version 8.2.

>       return click.testing.CliRunner(mix_stderr=False)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
E       TypeError: CliRunner.__init__() got an unexpected keyword argument 'mix_stderr'

See: https://github.com/pallets/click/pull/2523